"""
core/emg_classifier.py
----------------------
Trains the SVM gesture classifier and saves the model + scaler to disk.

This is a run-once script, not an importable module. Run it whenever the
dataset changes (new gestures added, samples regenerated) to produce fresh
model files. The rest of the system loads these files at startup.

Pipeline:
  1. Load dataset from models/emg_dataset.npz  (generated by emg_dataset.py)
  2. Scale features with StandardScaler
  3. Split 80/20 train/test (stratified per gesture)
  4. Train SVM (RBF kernel, C=10, gamma='scale')
  5. Evaluate — classification report + confusion matrix
  6. Save models/emg_model.pkl and models/emg_scaler.pkl

Architecture:
  Run after : emg_dataset.py (must exist before this runs)
  Produces  : models/emg_model.pkl, models/emg_scaler.pkl
  Loaded by : mode_manager.py at startup
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import joblib

from core.emg_dataset import load_dataset, LABEL_NAMES

# ── Load Dataset ──────────────────────────────────────────────────────────────
print("Loading dataset...")
X, y = load_dataset("emg_dataset.npz")
print(f"  X shape: {X.shape}, y shape: {y.shape}")


# ── Scale Features ────────────────────────────────────────────────────────────
# This is a critical step that beginners often skip and then wonder why accuracy
# is poor. Our 20 features are on very different scales:
#   - MAV values might be 0.05 to 0.9
#   - ZCR values might be 80 to 120
#   - WL values might be 8 to 125
#
# SVM is sensitive to feature scale — a feature with large numbers will
# dominate the others unfairly. StandardScaler fixes this by transforming
# each feature to have mean=0 and std=1, putting everything on equal footing.

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# ── Train / Test Split ────────────────────────────────────────────────────────
# We split data into 80% training and 20% testing.
# The model NEVER sees the test set during training — it's used only to
# evaluate how well the model generalizes to new, unseen data.
# random_state=42 just means the split is reproducible (same split every run).

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
    # stratify=y ensures the 80/20 split is applied equally per gesture class
)

print(f"\n  Training samples : {X_train.shape[0]}")
print(f"  Testing samples  : {X_test.shape[0]}")


# ── Train the SVM ─────────────────────────────────────────────────────────────
# kernel='rbf' — Radial Basis Function kernel. This is the standard choice
#   for EMG data. It handles non-linear relationships between features.
# C=10 — the regularization parameter. Higher C = model tries harder to
#   classify training data correctly (but risks overfitting). 10 is a
#   reasonable starting value for EMG.
# gamma='scale' — controls the influence radius of each training sample.
#   'scale' automatically sets it based on feature variance — good default.

print("\nTraining SVM classifier...")
clf = SVC(kernel='rbf', C=10, gamma='scale', random_state=42)
clf.fit(X_train, y_train)
print("  Training complete!")


# ── Evaluate ──────────────────────────────────────────────────────────────────
y_pred = clf.predict(X_test)

print("\n── Classification Report ──────────────────────────────")
print(classification_report(y_test, y_pred, target_names=LABEL_NAMES))
# This report shows per-gesture:
#   precision  = of all times it predicted "fist", how often was it right?
#   recall     = of all actual "fist" samples, how many did it catch?
#   f1-score   = harmonic mean of precision & recall (the main number to watch)
#   support    = how many test samples exist for that gesture


# ── Confusion Matrix ──────────────────────────────────────────────────────────
# A confusion matrix shows exactly WHICH gestures get confused with each other.
# Perfect classifier = bright diagonal, everything else dark.
# Off-diagonal bright spots = "model predicted X but actual was Y"

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=LABEL_NAMES)

fig, ax = plt.subplots(figsize=(7, 6))
disp.plot(ax=ax, colorbar=False, cmap="Blues")
ax.set_title("Confusion Matrix — Gesture Classifier", fontsize=13)
plt.tight_layout()
plt.show()


# ── Save Model & Scaler ───────────────────────────────────────────────────────
# We save both the trained model AND the scaler together.
# The scaler MUST be saved because at inference time (Step 6) we need to
# scale incoming data the exact same way we scaled training data.
# If we don't, the model will produce garbage predictions.

joblib.dump(clf,    "models/emg_model.pkl")
joblib.dump(scaler, "models/emg_scaler.pkl")
print("\nModel saved to emg_model.pkl")
print("Scaler saved to emg_scaler.pkl")